name: PR checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read  # This is required for the label PR action
  pull-requests: write # This is required for the label PR action

jobs:
  validate-pr-title:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'true'
          #custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "chore", "revert": "revert", "wip": "WIP"}'
          #add_scope_label: 'true'
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        id: label-prs
        uses: actions/labeler@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
