on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  GOTELEMETRY: off
  CGO_ENABLED: 0

name: Release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
    - name: Run release-please
      id: release
      uses: googleapis/release-please-action@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: go

  goreleaser:
    name: GoReleaser
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ needs.release-please.outputs.tag_name }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'
        check-latest: true
      id: go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        version: '~> v2'
        args: release --clean
        workdir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ needs.release-please.outputs.tag_name }}
